[Bug Fix] Fix Concurrency issue with volatile fields
apache/bookkeeper pull request #2677
Opened 2021-04-02 18:14 UTC by aahmed-se

### Motivation

The ConcurrentMap are doing increment and decrement operations on volatile primitive fields. This is not threadsafe.

### Changes

* Use AtomicIntegerFieldUpdater to replace increment and decrement operations.

2021-04-02 18:21 UTC, eolivelli requested changes
Very good.
I left one comment.
Do we have the same code in Pulsar?

2021-04-02 18:21 UTC, eolivelli commented on bookkeeper-server/src/main/java/org/apache/bookkeeper/util/collections/ConcurrentLongHashSet.java
> +                for (long l : table) {
Thi s is creating an Iterator, can we save this allocation? 
Also the JVM is very good in dealing with counted loops

2021-04-02 19:26 UTC, pkumar-singh commented on bookkeeper-server/src/main/java/org/apache/bookkeeper/util/collections/ConcurrentLongHashMap.java
> +                            sizeUpdater.incrementAndGet(this);
Why there is thread safety concern here while lock is acquired at line 298.  `long stamp = writeLock();`

2021-04-02 20:36 UTC, merlimat requested changes
The current code is thread safe, the increments of counters are done while holding the write lock

2021-04-03 11:58 UTC, aahmed-se commented
ok will close is pr then.

2021-04-03 11:58 UTC, closed without merging