Add throttle for rebuild entryMetadataMap
apache/bookkeeper pull request #2963
Opened 2021-12-25 02:32 UTC by hangc0276

### Motivation
When a bookie restart, the garbageCollectorThread will rebuild entryMetadataMap from all the entry log files in ledger directory. For normal case, it will extract the EntryLogMetadata from the index in entry log file. However, if there's no index, then fallback to scanning the entry log file. 

In user's production environment, the log files without index occupied 4%. The total entry log files is 80000, and the log files without index is 3000. The default entry log file size is 2GB, and the garbageCollectorThread will read 3000 * 2GB = 6TB data without speed limit, which will cause ledger disk IO util runs high for dozens of minutes and affect ledger read and write latency.

### Modification
1. Add read speed rate limiter for scanning entry log file in entryMetadataMap rebuild.

2021-12-25 07:19 UTC, nicoloboschi approved these changes
LGTM

2021-12-25 10:19 UTC, eolivelli requested changes
Overall lgtm

But I left one comment

2021-12-25 10:19 UTC, eolivelli commented on bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/EntryLogger.java
> +        } catch (Exception e) {
Can we catch specific exceptions here?

2021-12-27 01:30 UTC, hangc0276 commented
rerun failure checks

2021-12-27 12:27 UTC, hangc0276 commented
rerun failure checks

2021-12-28 06:18 UTC, hangc0276 commented
rerun failure checks

2021-12-29 01:04 UTC, hangc0276 commented
rerun failure checks

2022-01-05 01:17 UTC, hangc0276 commented
rerun failure checks

2022-01-05 07:16 UTC, eolivelli approved these changes
Lgtm

2022-01-05 07:17 UTC, eolivelli commented on bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/EntryLogger.java
> +            return extractEntryLogMetadataFromIndex(entryLogId);
I wonder if you could add a test that injects a failure here using PowerMock and test that the bookie works even if we fall into the catch clause

2022-02-14 19:40 UTC, dlg99 commented
@hangc0276 please rebase/resolve conflicts

2022-02-15 01:52 UTC, hangc0276 commented
rerun failure checks

2022-02-15 02:16 UTC, hangc0276 commented
rerun failure checks

2022-02-17 10:11 UTC, hangc0276 commented
rerun failure checks

2022-02-19 11:17 UTC, hangc0276 commented
rerun failure checks

2022-03-10 00:04 UTC, merged