support change compaction rate dynamically, issue #3147
apache/bookkeeper pull request #3151
Opened 2022-03-28 17:47 UTC by junedo

Descriptions of the changes in this PR:

### Motivation

when disk will be full for compaction rate of limiter  is too small , we want change the  rate dynamically by rest admin api without restart this bookie. 

### Changes

get and reset the rate of limiter from server config before compact one entry log file 

Master Issue: #3147

2022-03-30 03:11 UTC, gaozhangmin commented
@junedo  There are checkStyle violation 
```
Error:  /home/runner/work/bookkeeper/bookkeeper/bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/GarbageCollectorThread.java:497: Trailing whitespace [RegexpSingleline]
```

2022-03-30 03:18 UTC, gaozhangmin commented
@junedo  Do we have restful api for updating configuration now.

2022-03-30 03:30 UTC, gaozhangmin commented
> @junedo Do we have restful api for updating configuration now ?

I noticed the result api updating configuration.

2022-03-30 06:28 UTC, gaozhangmin approved these changes

2022-04-04 05:48 UTC, junedo commented
> configuration

yes, we can change configuration by rest admin api now.

2022-04-04 05:48 UTC, junedo commented
> @junedo There are checkStyle violation
> 
> ```
> Error:  /home/runner/work/bookkeeper/bookkeeper/bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/GarbageCollectorThread.java:497: Trailing whitespace [RegexpSingleline]
> ```

fixed

2022-08-25 02:09 UTC, StevenLuMT requested changes
do we need add testcase for new method : resetRate and getRate ?

2024-05-04 07:48 UTC, shoothzj commented
@junedo WDYT about @StevenLuMT's review opinion? are you still interested in this?

2024-06-13 08:16 UTC, shoothzj commented
closed by no updates.

2024-06-13 08:16 UTC, closed without merging

2024-06-13 08:16 UTC, shoothzj commented
Feel free to reopen it.