Add get under replicated ledger count
apache/bookkeeper pull request #3228
Opened 2022-04-21 02:43 UTC by hangc0276

### Motivation
Fix #3224 

### Changes
Add flag for `ListUnderreplicatedCmd` to control only display under replicated ledgers count

2022-04-22 03:18 UTC, hangc0276 commented
ping @dlg99  @eolivelli @zymap , Please help take a look, thanks.

2022-04-24 01:44 UTC, zymap reviewed
Add a test?

2022-04-24 12:31 UTC, eolivelli approved these changes
Awesome

2022-04-24 13:50 UTC, hangc0276 commented
> Add a test?

@zymap  I have added a test to cover the change.

2022-04-24 14:36 UTC, hangc0276 commented
rerun failure checks

2022-04-24 15:05 UTC, nicoloboschi requested changes

2022-04-24 15:05 UTC, nicoloboschi commented on bookkeeper-server/src/main/java/org/apache/bookkeeper/tools/cli/commands/autorecovery/ListUnderReplicatedCommand.java
> +        @Parameter(names = {"-c", "--onlyDisplayLedgerCount"},
we should keep the same name format of the other options (all lowercase)

2022-04-24 15:17 UTC, nicoloboschi requested changes

2022-04-24 15:17 UTC, nicoloboschi commented on bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/BookieShell.java
> +            opts.addOption("c", "onlyDisplayLedgerCount", false, "Only display underreplicated ledger count");
Lowercase as well?

2022-04-25 00:34 UTC, hangc0276 commented
rerun failure checks

2022-04-25 01:22 UTC, zymap approved these changes

2022-04-25 22:50 UTC, dlg99 approved these changes
Thank you!

It should be faster at least because it skips console output.
I thought about doing something along the lines of getting count of children nodes of hierarchical metadata manager to avoid extra calls to get all children nodes but let's start here and improve if it is still super slow on large clusters.

2022-04-25 22:51 UTC, dlg99 commented on site3/website/docs/reference/cli.md
> +| -c,--onlyDisplayLedgerCount | Only display underreplicated ledger count |
```suggestion
| -c,--onlydisplayledgercount | Only display underreplicated ledger count | 
```

2022-04-25 22:52 UTC, dlg99 commented on bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/BookieShell.java
> +            final boolean onlyDisplayLedgerCount = cmdLine.hasOption("onlyDisplayLedgerCount");
```suggestion
            final boolean onlyDisplayLedgerCount = cmdLine.hasOption("onlydisplayledgercount");
```

2022-04-25 22:58 UTC, dlg99 requested changes
Please add a test (see `ListUnderReplicatedCommandTest`)

2022-04-26 03:19 UTC, hangc0276 commented
> Please add a test (see `ListUnderReplicatedCommandTest`)
 
I have been add test `testOnlyDisplayLedgerCount`. Please help take a look, thanks a lot @dlg99

2022-04-26 03:19 UTC, hangc0276 commented
rerun failure checks

2022-04-26 06:15 UTC, dlg99 approved these changes

2022-04-26 06:17 UTC, merged