[website]fix website mailing_lists_url/slack_url #3534
apache/bookkeeper pull request #3535
Opened 2022-10-15 13:58 UTC by zwOvO

Descriptions of the changes in this PR:
The community related variables are not replaced

### Motivation
Poor user experience

### Changes
1、modify Upgrade page template variables
2、add  variables to config

Master Issue: #3534

![image](https://user-images.githubusercontent.com/18533252/195989997-63ac71d3-8d2a-425d-9c45-f0816f18cd80.png)

2022-10-15 15:49 UTC, nicoloboschi approved these changes

2022-10-15 23:21 UTC, StevenLuMT approved these changes
LGTM

2022-10-17 07:27 UTC, nicoloboschi requested changes
It's better to use relative paths

2022-10-17 07:27 UTC, nicoloboschi commented on site3/website/docs/admin/upgrade.md
> +> If you have questions about upgrades (or need help), please feel free to reach out to us by [mailing list]({{ site.mailing_lists_url }}) or [Slack Channel]({{ site.slack_url }}).
```suggestion
> If you have questions about upgrades (or need help), please feel free to reach out to us by [mailing list](/community/mailing-lists) or [Slack Channel](/community/slack).
```

2022-10-17 08:51 UTC, nicoloboschi approved these changes

2022-10-20 00:36 UTC, merged