Journal queue size dropped down to negative
apache/bookkeeper pull request #3650
Opened 2022-11-16 03:02 UTC by gaozhangmin

Journal queue size dropped down to negative
![image](https://user-images.githubusercontent.com/9278488/202073157-336cae48-fe9a-49d6-92e2-83b768a33885.png)

2022-11-16 07:35 UTC, gaozhangmin commented
rerun failure checks

2022-11-18 03:08 UTC, gaozhangmin commented on bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/Journal.java
> -                            journalStats.getJournalQueueSize().dec();
Here we don't need to decrease queue size, the queue size is decreased here.
```
if (qe != null) {
                            journalStats.getJournalQueueSize().dec();
                            journalStats.getJournalQueueStats()
                                .registerSuccessfulEvent(MathUtils.elapsedNanos(qe.enqueueTime), TimeUnit.NANOSECONDS);
                        }

```

2022-11-25 04:52 UTC, hangc0276 requested changes
There are many places to reduce the JournalQueueSize number, we'd better take a deep look at the logic.

2023-01-19 09:14 UTC, gaozhangmin commented
rerun failure checks

2023-03-22 07:02 UTC, closed without merging