Fix JAVA_HOME would be not set
apache/bookkeeper pull request #3651
Opened 2022-11-16 03:21 UTC by gaozhangmin

`source ${BK_CONFDIR}/bkenv.sh` should be precede in order to get proper JAVA_HOME variable

2022-11-18 01:10 UTC, zymap requested changes
As the comment said: `Set JAVA_HOME here to override the environment setting`. It is used to override the default value, so it shouldn't precede.

2022-11-18 05:32 UTC, gaozhangmin commented
There would be a case where we don't invoke common.sh or bookkeeper.sh from bookkeeper-daemon script. so the env settings which are set in  bkenv.sh would be useless.

2022-11-25 04:39 UTC, hangc0276 commented
> There would be a case where we don't invoke common.sh or bookkeeper.sh from bookkeeper-daemon script

> There would be a case where we don't invoke common.sh or bookkeeper.sh from bookkeeper-daemon script

In bookkeeper-daemon.sh, we will call bookkeeper.sh

2022-11-25 04:40 UTC, hangc0276 requested changes
> As the comment said: Set JAVA_HOME here to override the environment setting. It is used to override the default value, so it shouldn't precede.

+1

2022-11-28 08:59 UTC, closed without merging