Fix ForceWriteRequest recycle problem
apache/bookkeeper pull request #3749
Opened 2023-01-19 07:32 UTC by gaozhangmin

The ForceWriteRequest is recycled without resetting properties.

![image](https://user-images.githubusercontent.com/9278488/213381537-7b2e6c9d-a7a6-4905-b343-58983ac168e8.png)

2023-01-19 07:36 UTC, eolivelli approved these changes
LGTM

2023-01-19 14:57 UTC, horizonzy reviewed
The basic type will be overridden at the next reuse. I think we needn't to reset the basic type value. It doesn't help GC work. And the old value can help to trace problems when we dump.

2023-01-28 09:28 UTC, StevenLuMT approved these changes
LGTM

2023-01-31 07:35 UTC, hangc0276 requested changes
+1 for no need to reset the basic type values.

2023-02-01 05:28 UTC, closed without merging