[fix][ci] Fix OWASP Dependency Check download by using NVD API key
apache/bookkeeper pull request #4473
Opened 2024-07-27 08:09 UTC by shoothzj

See more in https://github.com/apache/pulsar/pull/22999. Thanks for @lhotari

2024-07-28 00:00 UTC, shoothzj commented
@lhotari It seems download is still failed, do we need to merge this first?

2024-07-28 07:04 UTC, lhotari requested changes

2024-07-28 07:04 UTC, lhotari commented on pom.xml
> +    <dependency-check-maven.version>10.0.1</dependency-check-maven.version>
Should use at least 10.0.2 version

2024-07-28 07:08 UTC, lhotari commented
> @lhotari It seems download is still failed, do we need to merge this first?

Yes. Another option would be to create the PR branch to apache/bookkeeper so that it has access to the secret. The dependency check version must be at least 10.0.2 (there's another Pulsar PR explaining that).

2024-07-28 08:59 UTC, shoothzj commented
@lhotari Thanks, I see your description in https://github.com/apache/pulsar/pull/23012.

I suggest we can merge this pr first.

> There's a [mandatory upgrade notice](https://github.com/jeremylong/DependencyCheck?tab=readme-ov-file#mandatory-upgrade-notice) about upgrading to 10.0.2 version.

2024-07-28 11:34 UTC, lhotari commented
> I suggest we can merge this pr first.

That works for me, but why not just upgrade to 10.0.2 in this PR?

2024-07-28 11:34 UTC, lhotari approved these changes

2024-07-28 11:35 UTC, lhotari commented
Looks like 10.0.2 is used in this PR, LGTM.

2024-07-28 11:35 UTC, lhotari approved these changes

2024-07-28 12:25 UTC, lhotari commented
There's a error building the docker image
```
[INFO] Package netcat is a virtual package provided by:
[INFO]   netcat-traditional 1.10-48
[INFO]   netcat-openbsd 1.226-1ubuntu2
[INFO] 
[INFO] E: Package 'netcat' has no installation candidate
```
I believe `netcat-openbsd` should be used.

2024-07-29 08:00 UTC, lhotari approved these changes

2024-07-29 09:10 UTC, merged